### ISSUE TITLE
New Initiatives button is drawn right over top of the Cherish logo

### ISSUE THREAD

**Issue by chrisco23** [mtr-cherish/cherish#112]
![overlap_and_blank](https://cloud.githubusercontent.com/assets/241907/8575804/d3360614-2552-11e5-87f9-c29fcb48e3a8.jpg)

This is Chrome Version 43.0.2357.130 (64-bit) on Kubuntu 14.04.

**Comment by iamlasse** [comment]
Yes when i created that quick feature the logo was placed elsewhere. Maybe we can push it down a bit to sit below as well as lead to initiatives page if not currently on that page. I was thinking if it was possible to scroll the page and somehow highlight the most recent initiatives. If you leave your browser open and a bunch of i initiatives are created it will update the count.

**Comment by chrisco23** [comment]
First idea that comes to my mind is always displaying initiatives in reverse chron., and possibly a little star at the corner or border or something to indicate new initiatives.  New initiatives are new since last login too or only new since current login??  Also, I'm not sure if it's what you meant but I think any sort of scrolling without the user doing anything could be kind of jarring.

**Comment by iamlasse** [comment]
Currently its by latest login. I think the var is lastUpdated. But it was a bit since i looked at that. I like the idea of some subtle indication on new initiatives.

**Comment by weslers** [comment]
What if we removed the button on one half of the page have a full image banner image of other user iniativiaties on the other half have the form the user fills in. There is no point sending the user to this page toake them click another button the form should be there to fill in.

**Comment by jeffshaver** [comment]
@iamlasse why do we even have this feature? maybe I am missing out on the usefulness?
