### ISSUE TITLE
No forgot password functionality on cherish.meteor.com

### ISSUE THREAD

**Issue by chrisco23** [mtr-cherish/cherish#114]
I don't see any way to recover a password on cherish.meteor.com

**Comment by iamlasse** [comment]
I think it comes with accounts-base but hasnt been implemented yet. Feel free to add yourself and it will be moved to ready.

**Comment by chrisco23** [comment]
On another project I use ian:accounts-ui-bootstrap-3.  Was this package considered for cherish at all?  It gives you Forgot Password, Login with Facebook, Google, Github, ... things all out of the box.  Then, not sure if it's cleanest, but because I'm moving to material design, I use https://github.com/FezVrasta/bootstrap-material-design

**Comment by chrisco23** [comment]
Here's the ian:accounts-ui-bootstrap-3 straight out of the box
![signin_ui-accounts](https://cloud.githubusercontent.com/assets/241907/8578814/d026e368-2565-11e5-94e7-e0d5a510633f.jpg)

**Comment by jeffshaver** [comment]
@chrisco23 i am a personal fan of having a dedicated login/register page instead of a drop down. I am also not a huge bootstrap fan either. Plus, we are already using materialize. We should get "forgot password" functionality added. This seems like a good article on doing this: https://gentlenode.com/journal/meteor-2-build-a-complete-registration-system/3

**Comment by chrisco23** [comment]
If we don't use accounts-ui-bootstrap-3, any objection to using accounts-entry package?  I really don't see any reason to reinvent the wheel, piecemeal-like.  And there are plenty of reasons not to:
1.  good well-tested code already used in production already exists
2.  less work for us
3.  familiar UI/UX for our users

That's one of the perks of Meteor:  one doesn't have to build auth from scratch.

**Comment by jeffshaver** [comment]
@chrisco23 my issue with that package is that it has 86 open issues, 32 pull requests and hasn't been touched in 3 months. But I guess I could be swayed either way. Would like @iamlasse, @mariocatch and everyone elses opinion on this.

**Comment by chrisco23** [comment]
Another good candidate, I believe, is useraccounts:materialize, though I've
not used it before.
