### ISSUE TITLE
Failed to download decoded font

### ISSUE THREAD

**Issue by chrisco23** [mtr-cherish/cherish#135]
I'm seeing these all over the place in Chrome Dev Tools on Kubuntu--anybody else?:

![failed_to_decode_downloaded_font](https://cloud.githubusercontent.com/assets/241907/8600934/a6c7b426-261d-11e5-925f-667af9ff95bb.jpg)

**Comment by weslers** [comment]
I have been getting thus from the start

**Comment by jeffshaver** [comment]
Yeah. I have been getting this for quite a while as well.

**Comment by iamlasse** [comment]
Same here, not sure where it stems from.

**Comment by ZachStoltz** [comment]
I know when I use bootstrap, if I don't have the font directory, I think one directory below the root directory it comes back with this error.  Maybe it is something similar with our materialize stuff?
