### ISSUE TITLE
Prevent logged in users from accessing the login/register routes and remove logout button from the login page

### ISSUE THREAD

**Issue by weslers** [mtr-cherish/cherish#140]
If you login and go back a page the logout button is unstyled

<img width="663" alt="screen shot 2015-07-10 at 21 34 47" src="https://cloud.githubusercontent.com/assets/1480002/8628514/96d82d96-274b-11e5-8312-b7b2d42a000a.png">

**Comment by jeffshaver** [comment]
I don't think we should even let a logged in user go to the `/login` route. Doesn't make any sense. Similarly, they shouldn't be able to get to the `/register` route.

**Comment by ZachStoltz** [comment]
I agree, should redirect them to the homepage if they try navigating to `/login` or `/register` and are already authenticated.

**Comment by weslers** [comment]
Agree about the redirect but as a matter of course should probably have the button styled anyway

**Comment by ZachStoltz** [comment]
I wouldn't think to do the button styling.  I would make this ticket for redirecting the user away from the login.  There will be no point for the logout button from this view when that happens.

**Comment by jeffshaver** [comment]
@weslers if you don't let logged in users get there, there is no reason to have a logout button.

This ticket should fix the following:
- [ ] Prevent users from accessing the login route
- [ ] Prevent users from accessing the register route
- [ ] Remove the logout button from the login route

**Comment by weslers** [comment]
Would a logout button be used elsewhere though I guess its just me been picky about the UI its a button element and should look and act like other button elements

**Comment by ZachStoltz** [comment]
There is a logout within the dropdown where the user name is provided.  I think that would be enough to cover it?

**Comment by jeffshaver** [comment]
@weslers a logout button is in the dropdown. the one on the login template needs to be removed. It serves no purpose.

**Comment by iamlasse** [comment]
Logout and login in the same view, not only confusing, but very ux wrong lol
