### ISSUE TITLE
Updated readme to includes project docs

### ISSUE THREAD

**Issue by dcworldwide** [mtr-cherish/cherish#29]
Please update to readme to answer the following:
- where is the project roadmap
- where are project discussions held (slack?)

Keen to hear more. I'd like to see this project become a telescope like initiative, where any project could deploy it to track user feature requests / feature voting.

**Comment by Vaqxin** [comment]
I believe the project roadmap is posted on a private board via Trello. Just found this project on Crater.io and I'm looking to get involved as well.

**Comment by trustieee** [comment]
Hello,

Cherish's roadmap is currently private, but development is being kept open source. We will have a better readme soon. If there is enough interest in the project then we'll consider opening up our Trello board. For now, Github is the best place to have the conversation.

**Comment by trustieee** [comment]
Readme updated with pertinent project information.
