### ISSUE TITLE
Scroll position is preserved from landing page to each Initiative page

### ISSUE THREAD

**Issue by trustieee** [mtr-cherish/cherish#92]
When a user scrolls down on the landing page, then clicks an Initiative, they are scrolled down that amount on the Initiative page, usually placing them at the footer instead of the top of the page.

**Comment by jeffshaver** [comment]
Should just be able to add this package: https://atmospherejs.com/okgrow/iron-router-autoscroll

**Comment by chrisco23** [comment]
Since I only had a one-line change to initiativeShow.js, I did "git rebase origin/dev", merged in my window.scrollTo(0,0), did a commit and push.  Please let me know if any issue with that.
